# Generated by Django 5.0.6 on 2025-01-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customuser_role_alter_module_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
