# Generated by Django 5.0.6 on 2025-01-01 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_role_alter_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_students', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('admin', 'admin'), ('student', 'student')], max_length=255, null=True),
        ),
    ]
