# Generated by Django 5.0.6 on 2025-01-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_course_students_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student'), ('teacher', 'teacher')], max_length=255, null=True),
        ),
    ]
