# Generated by Django 5.0.6 on 2025-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_course_students_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('instructor', 'instructor'), ('student', 'student')], max_length=255, null=True),
        ),
    ]
