# Generated by Django 5.0.6 on 2025-01-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
