# Generated by Django 5.0.6 on 2025-01-02 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_quiz_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('instructor', 'instructor'), ('student', 'student')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='app.module', verbose_name='Module'),
        ),
    ]
